export const pluginSpecPackagesName: "miot.plugin.spec";
export const pluginSpecModel: "miot.switch.spec";
export const pluginSTDSpecPluginID: 1006883;
export const cameraSpecPackagesName: "com.xiaomi.stdcamera";
export const cameraSpecModel: "miot.camera.spec";
export const cameraSTDSpecPluginID: 1009931;
export const doorbellSpecPackagesName: "miot.doorbell.spec";
export const doorbellSpecModel: "miot.doorbell.spec";
export const doorbellSTDSpecPluginID: 1013368;