import MoreSetting from "./MoreSetting";
import FirmwareUpgrade from "./FirmwareUpgrade";
import FirmwareUpgradeAuto from "./FirmwareUpgradeAuto";
import FirmwareUpgradeRecord from "./FirmwareUpgradeRecord";
import CommonSetting from "./CommonSetting";
import { SETTING_KEYS } from "./CommonSetting";
import CommonSettingPage from "./CommonSettingPage";
import CurtainGroupPage from "./CurtainGroupPage";
import CloudStorage from "./CloudStorage";
export { MoreSetting, FirmwareUpgrade, FirmwareUpgradeAuto, FirmwareUpgradeRecord, CommonSetting, SETTING_KEYS, CommonSettingPage, CurtainGroupPage, CloudStorage };