import Host from "miot/Host";
const getStrings = strings => {
  const language = Host.locale.language;
  return strings[language] || strings['zh'];
}
// 为了 autoComplete
let strings = {
  setting: '',
  featureSetting: '',
  commonSetting: '',
  name: '',
  location: '',
  memberSet: '',
  share: '',
  btGateway: '',
  voiceAuth: '',
  ifttt: '',
  firmwareUpgrade: '',
  more: '',
  help: '',
  legalInfo: '',
  deleteDevice: '',
  autoUpgrade: '',
  checkUpgrade: '',
  security: '',
  feedback: '',
  timezone: '',
  addToDesktop: ''
}
strings = getStrings({
  zh: {
    setting: '设置',
    featureSetting: '功能设置',
    commonSetting: '通用设置',
    name: '设备名称',
    location: '位置管理',
    memberSet: '按键设置',
    share: '设备共享',
    btGateway: '蓝牙网关',
    voiceAuth: '语音授权',
    ifttt: '智能场景',
    firmwareUpgrade: '固件升级',
    more: '更多设置',
    help: '使用帮助',
    legalInfo: '法律信息',
    deleteDevice: '删除设备',
    autoUpgrade: '固件自动升级',
    checkUpgrade: '检查固件升级',
    security: '安全设置',
    feedback: '反馈问题',
    timezone: '设备时区',
    addToDesktop: '添加桌面快捷方式',
  },
  zh_tw: {
    setting: '設定',
    featureSetting: '功能設定',
    commonSetting: '一般設定',
    name: '裝置名稱',
    location: '位置管理',
    memberSet: '按鍵設定',
    share: '裝置共用',
    btGateway: '藍牙網關',
    voiceAuth: '語音授權',
    ifttt: '智能場景',
    firmwareUpgrade: '韌體更新',
    more: '更多設定',
    help: '使用説明',
    legalInfo: '法律資訊',
    deleteDevice: '刪除裝置',
    autoUpgrade: '韌體自动更新',
    checkUpgrade: '檢查韌體更新',
    security: '安全設定',
    feedback: '反饋問題',
    timezone: '裝置時區',
    addToDesktop: '新増捷徑至桌面',
  },
  zh_hk: {
    setting: '設定',
    featureSetting: '功能設定',
    commonSetting: '一般設定',
    name: '裝置名稱',
    location: '位置管理',
    memberSet: '按鍵設定',
    share: '裝置共用',
    btGateway: '藍牙網關',
    voiceAuth: '語音授權',
    ifttt: '智慧場景',
    firmwareUpgrade: '韌體更新',
    more: '更多設定',
    help: '使用説明',
    legalInfo: '法律資訊',
    deleteDevice: '刪除裝置',
    autoUpgrade: '韌體自动更新',
    checkUpgrade: '檢查韌體更新',
    security: '安全設定',
    feedback: '反饋問題',
    timezone: '裝置時區',
    addToDesktop: '新增捷徑到桌面',
  },
  en: {
    setting: 'Settings',
    featureSetting: 'Shortcut settings',
    commonSetting: 'General settings',
    name: 'Device name',
    location: 'Manage locations',
    memberSet: 'Key settings',
    share: 'Shared devices',
    btGateway: 'BLE Gateway',
    voiceAuth: 'Voice authorization',
    ifttt: 'Automation',
    firmwareUpgrade: 'Firmware updates',
    more: 'Additional settings',
    help: 'Help',
    legalInfo: 'Legal information',
    deleteDevice: 'Remove device',
    autoUpgrade: 'Automatically update firmware',
    checkUpgrade: 'Check for firmware updates',
    security: 'Security settings',
    feedback: 'Feedback',
    timezone: 'Device time zone',
    addToDesktop: 'Add to Home screen',
  },
  ko: {
    setting: '설정',
    featureSetting: '바로가기 설정',
    commonSetting: '일반 설정',
    name: '기기 이름',
    location: '위치 관리',
    memberSet: '按鍵設定', //TODO:
    share: '공유된 기기',
    btGateway: 'BLE 게이트웨이',
    voiceAuth: '語音授權', //TODO:
    ifttt: '자동화',
    firmwareUpgrade: '펌웨어 업데이트',
    more: '추가 설정',
    help: '도움말',
    legalInfo: '법률 정보',
    deleteDevice: '기기 제거',
    autoUpgrade: '韌體自动更新', //TODO:
    checkUpgrade: '펌웨어 업데이트 확인',
    security: '보안 설정',
    feedback: '피드백',
    timezone: '디바이스 시간대',
    addToDesktop: '홈 화면에 추가',
  },
});
export default strings;