import locale from "miot/host/locale";
const placeholderRegex = /(\{[\d|\w]+\})/;
const getStrings = (strings) => {
  const language = locale.language;
  return strings[language] || strings['en'];
};
const formatString = (str, ...valuesForPlaceholders) => {
  return (str || '')
    .split(placeholderRegex)
    .filter((textPart) => !!textPart)
    .map((textPart) => {
      if (textPart.match(placeholderRegex)) {
        const matchedKey = textPart.slice(1, -1);
        let valueForPlaceholder = valuesForPlaceholders[matchedKey];
        // If no value found, check if working with an object instead
        if (valueForPlaceholder == undefined) {
          const valueFromObjectPlaceholder = valuesForPlaceholders[0][matchedKey];
          if (valueFromObjectPlaceholder !== undefined) {
            valueForPlaceholder = valueFromObjectPlaceholder;
          } else {
            // If value still isn't found, then it must have been undefined/null
            return valueForPlaceholder;
          }
        }
        return valueForPlaceholder;
      }
      return textPart;
    }).join('');
};
// 为了 autoComplete
let strings = {
  setting: '',
  featureSetting: '',
  commonSetting: '',
  name: '',
  location: '',
  memberSet: '',
  share: '',
  btGateway: '',
  voiceAuth: '',
  ifttt: '',
  firmwareUpgrade: '',
  more: '',
  help: '',
  legalInfo: '',
  deleteDevice: '',
  autoUpgrade: '',
  checkUpgrade: '',
  security: '',
  networkInfo: '',
  feedback: '',
  timezone: '',
  addToDesktop: '',
  // MHDatePicker
  cancel: '',
  ok: '',
  am: '',
  pm: '',
  months: '',
  days: '',
  hours: '',
  minutes: '',
  seconds: '',
  month: '',
  day: '',
  hour: '',
  minute: '',
  second: '',
  yearUnit: '',
  monthUnit: '',
  dayUnit: '',
  hourUnit: '',
  minuteUnit: '',
  secondUnit: '',
  dateSubTitle: '',
  time24SubTitle: '',
  time12SubTitle: '',
  singleSubTitle: '',
  firmwareUpgradeExit: '',
  firmwareUpgradeUpdate: '',
  firmwareUpgradeLook: '',
  firmwareUpgradeForceUpdate: '',
  firmwareUpgradeForceUpdating: '',
  firmwareUpgradeNew_pre: '',
  firmwareUpgradeNew_sub: '',
  handling: '',
  error: '',
  createLightGroup: '',
  linkDevice: '',
  noSuppurtedLinkageDevice: '',
  noSuppurtedLinkageTip: '',
  supportedLinkageDevices: '',
  linkageDistanceTip: '',
  linkageRemoveTip: '',
  link: '',
  removeLink: '',
  linkFail: '',
  removeLinkFail: '',
  linkConfirm: '',
  removeLinkConfirm: '',
  linking: '',
  pluginVersion: '',
  helpAndFeedback: ''
};
strings = getStrings({
  zh: {
    setting: '设置',
    featureSetting: '功能设置',
    commonSetting: '通用设置',
    name: '设备名称',
    location: '位置管理',
    memberSet: '按键设置',
    share: '设备共享',
    btGateway: '蓝牙网关',
    voiceAuth: '语音授权',
    ifttt: '智能场景',
    firmwareUpgrade: '固件升级',
    more: '更多设置',
    help: '使用帮助',
    legalInfo: '法律信息',
    deleteDevice: '删除设备',
    autoUpgrade: '固件自动升级',
    checkUpgrade: '检查固件升级',
    security: '安全设置',
    networkInfo: '网络信息',
    feedback: '反馈问题',
    timezone: '设备时区',
    addToDesktop: '添加桌面快捷方式',
    // MHDatePicker
    cancel: '取消',
    ok: '确定',
    am: '上午',
    pm: '下午',
    months: '个月',
    days: '天',
    hours: '小时',
    minutes: '分钟',
    seconds: '秒钟',
    month: '个月',
    day: '天',
    hour: '小时',
    minute: '分钟',
    second: '秒钟',
    yearUnit: '年',
    monthUnit: '月',
    dayUnit: '日',
    hourUnit: '时',
    minuteUnit: '分',
    secondUnit: '秒',
    dateSubTitle: '{0}年{1}月{2}日', // 2019年06月03日
    time24SubTitle: '{0}:{1}', // 11:43
    time12SubTitle: '{0} {1}:{2}', // 上午 11:43
    singleSubTitle: '{0} {1}', // 5 小时
    // 升级相关
    firmwareUpgradeExit: '退出',
    firmwareUpgradeUpdate: '升级',
    firmwareUpgradeLook: '去看看',
    firmwareUpgradeForceUpdate: '由于您当前的设备固件版本过低，一些功能可能无法正常使用。请升级至最新版本，以体验更丰富的功能',
    firmwareUpgradeForceUpdating: '您的设备正在升级，请稍后，以体验更丰富的功能',
    firmwareUpgradeNew_pre: '检测到设备有最新固件版本',
    firmwareUpgradeNew_sub: '，是否升级',
    handling: '操作中...',
    error: '处理失败，请稍后再试',
    createLightGroup: '创建灯组（新）',
    manageLightGroup: '灯组管理（新）',
    deleteLightGroup: '解散灯组',
    linkDevice: '关联设备',
    noSuppurtedLinkageDevice: '当前无可关联设备',
    noSuppurtedLinkageTip: '1.请确保在米家APP中已添加需要关联的设备，并按要求分配到对应房间下；\n2.请将需要关联的蓝牙设备与本设备保持在一定范围内，否则将无法建立关联。',
    supportedLinkageDevices: '可关联如下设备',
    linkageDistanceTip: '请将需要关联的蓝牙设备与本设备保持在一定范围内，否则将无法建立关联',
    linkageRemoveTip: '如需更换关联的蓝牙设备，请先解除关联',
    link: '关联',
    removeLink: '解除关联',
    linkFail: '关联失败',
    removeLinkFail: '解除关联失败',
    linkConfirm: '确认关联该设备？',
    removeLinkConfirm: '确认解除关联？',
    linking: '正在关联...',
    pluginVersion: '插件版本号',
    helpAndFeedback: '帮助与反馈'
  },
  zh_tw: {
    setting: '設定',
    featureSetting: '裝置設定',
    commonSetting: '一般設定',
    name: '裝置名稱',
    location: '位置管理',
    memberSet: '按鍵設定',
    share: '裝置共用',
    btGateway: '藍牙網關',
    voiceAuth: '語音授權',
    ifttt: '智能場景',
    firmwareUpgrade: '韌體更新',
    more: '更多設定',
    help: '使用説明',
    legalInfo: '法律資訊',
    deleteDevice: '刪除裝置',
    autoUpgrade: '韌體自动更新',
    checkUpgrade: '檢查韌體更新',
    security: '安全設定',
    networkInfo: '網路資訊',
    feedback: '反饋問題',
    timezone: '裝置時區',
    addToDesktop: '新増捷徑至桌面',
    // MHDatePicker
    cancel: '取消',
    ok: '确定',
    am: '上午',
    pm: '下午',
    months: '个月',
    days: '天',
    hours: '小时',
    minutes: '分钟',
    seconds: '秒钟',
    month: '个月',
    day: '天',
    hour: '小时',
    minute: '分钟',
    second: '秒钟',
    yearUnit: '年',
    monthUnit: '月',
    dayUnit: '日',
    hourUnit: '时',
    minuteUnit: '分',
    secondUnit: '秒',
    dateSubTitle: '{0}年{1}月{2}日', // 2019年06月03日
    time24SubTitle: '{0}:{1}', // 11:43
    time12SubTitle: '{0} {1}:{2}', // 上午 11:43
    singleSubTitle: '{0} {1}', // 5 小时
    // 升级相关
    firmwareUpgradeExit: '退出',
    firmwareUpgradeUpdate: '升級',
    firmwareUpgradeLook: '看看',
    firmwareUpgradeForceUpdate: '由於您目前的用戶端版本過低，一些功能可能無法正常使用。 請升級最新版本，以體驗更豐富的功能',
    firmwareUpgradeForceUpdating: '您的裝置正在升級，請稍後，以體驗更豐富的功能',
    firmwareUpgradeNew_pre: '檢測到裝置有最新韌體版本',
    firmwareUpgradeNew_sub: '，是否升級',
    handling: '執行中...',
    error: '處理失敗，請重試',
    createLightGroup: 'Create light group(new)',
    manageLightGroup: 'Manage devices(new)',
    deleteLightGroup: 'Disband light group',
    linkDevice: 'Link devices',
    noSuppurtedLinkageDevice: 'No devices available for linking now',
    noSuppurtedLinkageTip: '1.Please make sure the device to link with has been added to the app, and is assigned to the preferred room.\n2.Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    supportedLinkageDevices: 'Can be linked with the following devices',
    linkageDistanceTip: 'Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    linkageRemoveTip: 'If the linked Bluetooth device needs to be changed, please remove link first.',
    link: 'Link',
    removeLink: 'Remove link',
    linkFail: 'Couldn\'t link',
    removeLinkFail: 'Couldn\'t remove the link',
    linkConfirm: 'Link with this device now?',
    removeLinkConfirm: 'Remove link now?',
    linking: 'Linking…',
    pluginVersion: '挿件版本號',
    helpAndFeedback: '幫助與反饋'
  },
  zh_hk: {
    setting: '設定',
    featureSetting: '裝置設定',
    commonSetting: '一般設定',
    name: '裝置名稱',
    location: '位置管理',
    memberSet: '按鍵設定',
    share: '裝置共用',
    btGateway: '藍牙網關',
    voiceAuth: '語音授權',
    ifttt: '智慧場景',
    firmwareUpgrade: '韌體更新',
    more: '更多設定',
    help: '使用説明',
    legalInfo: '法律資訊',
    deleteDevice: '刪除裝置',
    autoUpgrade: '韌體自动更新',
    checkUpgrade: '檢查韌體更新',
    security: '安全設定',
    networkInfo: '網路資訊',
    feedback: '反饋問題',
    timezone: '裝置時區',
    addToDesktop: '新增捷徑到桌面',
    // MHDatePicker
    cancel: '取消',
    ok: '确定',
    am: '上午',
    pm: '下午',
    months: '个月',
    days: '天',
    hours: '小时',
    minutes: '分钟',
    seconds: '秒钟',
    month: '个月',
    day: '天',
    hour: '小时',
    minute: '分钟',
    second: '秒钟',
    yearUnit: '年',
    monthUnit: '月',
    dayUnit: '日',
    hourUnit: '时',
    minuteUnit: '分',
    secondUnit: '秒',
    dateSubTitle: '{0}年{1}月{2}日', // 2019年06月03日
    time24SubTitle: '{0}:{1}', // 11:43
    time12SubTitle: '{0} {1}:{2}', // 上午 11:43
    singleSubTitle: '{0} {1}', // 5 小时
    // 升级相关
    firmwareUpgradeExit: '退出',
    firmwareUpgradeUpdate: '升級',
    firmwareUpgradeLook: '去看看',
    firmwareUpgradeForceUpdate: '由於您目前的用戶端版本過低，一些功能可能無法正常使用。 請升級最新版本，以體驗更豐富的功能',
    firmwareUpgradeForceUpdating: '您的裝置正在升級，請稍後，以體驗更豐富的功能',
    firmwareUpgradeNew_pre: '檢測到裝置有最新韌體版本',
    firmwareUpgradeNew_sub: '，是否升級',
    handling: '執行中...',
    error: '處理失敗，請重試',
    createLightGroup: 'Create light group(new)',
    manageLightGroup: 'Manage devices(new)',
    deleteLightGroup: 'Disband light group',
    linkDevice: 'Link devices',
    noSuppurtedLinkageDevice: 'No devices available for linking now',
    noSuppurtedLinkageTip: '1.Please make sure the device to link with has been added to the app, and is assigned to the preferred room.\n2.Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    supportedLinkageDevices: 'Can be linked with the following devices',
    linkageDistanceTip: 'Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    linkageRemoveTip: 'If the linked Bluetooth device needs to be changed, please remove link first.',
    link: 'Link',
    removeLink: 'Remove link',
    linkFail: 'Couldn\'t link',
    removeLinkFail: 'Couldn\'t remove the link',
    linkConfirm: 'Link with this device now?',
    removeLinkConfirm: 'Remove link now?',
    linking: 'Linking…',
    pluginVersion: '挿件版本號',
    helpAndFeedback: '幫助與反饋'
  },
  en: {
    setting: 'Settings',
    featureSetting: 'Device settings',
    commonSetting: 'General settings',
    name: 'Device name',
    location: 'Manage locations',
    memberSet: 'Key settings',
    share: 'Share device',
    btGateway: 'BLE Gateway',
    voiceAuth: 'Voice authorization',
    ifttt: 'Automation',
    firmwareUpgrade: 'Firmware updates',
    more: 'Additional settings',
    help: 'Help',
    legalInfo: 'Legal information',
    deleteDevice: 'Delete device',
    autoUpgrade: 'Automatically update firmware',
    checkUpgrade: 'Check for firmware updates',
    security: 'Security settings',
    networkInfo: 'Network info',
    feedback: 'Feedback',
    timezone: 'Device time zone',
    addToDesktop: 'Add to Home screen',
    // MHDatePicker
    cancel: 'Cancel',
    ok: 'Confirm',
    am: 'AM',
    pm: 'PM',
    months: 'months',
    days: 'days',
    hours: 'hours',
    minutes: 'minutes',
    seconds: 'seconds',
    month: 'month',
    day: 'day',
    hour: 'hour',
    minute: 'minute',
    second: 'second',
    yearUnit: '',
    monthUnit: '',
    dayUnit: '',
    hourUnit: '',
    minuteUnit: '',
    secondUnit: '',
    dateSubTitle: '{0}-{1}-{2}', // 2019-06-03
    time24SubTitle: '{0}:{1}', // 11:43
    time12SubTitle: '{1}:{2} {0}', // 11:43 am
    singleSubTitle: '{0} {1}', // 1 hour | 2 hours
    // 升级相关
    firmwareUpgradeExit: 'Exit',
    firmwareUpgradeUpdate: 'Update',
    firmwareUpgradeLook: 'Take a look',
    firmwareUpgradeForceUpdate: 'Current firmware may be too old to run some features. Update to the latest version for better experience.',
    firmwareUpgradeForceUpdating: 'Your device is updating, try again later',
    firmwareUpgradeNew_pre: 'Firmware update ',
    firmwareUpgradeNew_sub: ' available. Update now?',
    handling: 'Running…',
    error: 'Could not operate, please try again later',
    createLightGroup: 'Create light group(new)',
    manageLightGroup: 'Manage devices(new)',
    deleteLightGroup: 'Disband light group',
    linkDevice: 'Link devices',
    noSuppurtedLinkageDevice: 'No devices available for linking now',
    noSuppurtedLinkageTip: '1.Please make sure the device to link with has been added to the app, and is assigned to the preferred room.\n2.Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    supportedLinkageDevices: 'Can be linked with the following devices',
    linkageDistanceTip: 'Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    linkageRemoveTip: 'If the linked Bluetooth device needs to be changed, please remove link first.',
    link: 'Link',
    removeLink: 'Remove link',
    linkFail: 'Couldn\'t link',
    removeLinkFail: 'Couldn\'t remove the link',
    linkConfirm: 'Link with this device now?',
    removeLinkConfirm: 'Remove link now?',
    linking: 'Linking…',
    pluginVersion: 'Plugin version number',
    helpAndFeedback: 'Help & Feedback'
  },
  ko: {
    setting: '설정',
    featureSetting: '기기 설정',
    commonSetting: '일반 설정',
    name: '기기 이름',
    location: '위치 관리',
    memberSet: '버튼 설정',
    share: '기기 공유',
    btGateway: 'BLE 게이트웨이',
    voiceAuth: '음성 권한',
    ifttt: '자동화',
    firmwareUpgrade: '펌웨어 업데이트',
    more: '추가 설정',
    help: '도움말',
    legalInfo: '법률 정보',
    deleteDevice: '기기 제거',
    autoUpgrade: '펌웨어 자동 업데이트',
    checkUpgrade: '펌웨어 업데이트 확인',
    security: '보안 설정',
    networkInfo: '네트워크 정보',
    feedback: '피드백',
    timezone: '디바이스 시간대',
    addToDesktop: '홈 화면에 추가',
    // MHDatePicker
    cancel: 'Cancel',
    ok: 'Confirm',
    am: 'AM',
    pm: 'PM',
    months: 'months',
    days: 'days',
    hours: 'hours',
    minutes: 'minutes',
    seconds: 'seconds',
    month: 'month',
    day: 'day',
    hour: 'hour',
    minute: 'minute',
    second: 'second',
    yearUnit: '',
    monthUnit: '',
    dayUnit: '',
    hourUnit: '',
    minuteUnit: '',
    secondUnit: '',
    dateSubTitle: '{0}-{1}-{2}', // 2019-06-03
    time24SubTitle: '{0}:{1}', // 11:43
    time12SubTitle: '{1}:{2} {0}', // 11:43 am
    singleSubTitle: '{0} {1}', // 1 hour | 2 hours
    // 升级相关
    firmwareUpgradeExit: '나가기',
    firmwareUpgradeUpdate: '업데이트',
    firmwareUpgradeLook: '확인해보세요',
    firmwareUpgradeForceUpdate: '현재 펌웨어 버전이 너무 오래되었습니다. 몇몇 기능이 정상적으로 작동하지 않을 수 있습니다. 더 나은 사용을 위해 최신 버전으로 업데이트 하십시오.',
    firmwareUpgradeForceUpdating: '기기를 업데이트 중입니다. 나중에 다시 시도하십시오.',
    firmwareUpgradeNew_pre: '펌웨어 업데이트 ',
    firmwareUpgradeNew_sub: ' 가능, 지금 업데이트 하시겠습니까?',
    handling: '실행 중...',
    error: '다시 시도',
    createLightGroup: 'Create light group(new)',
    manageLightGroup: 'Manage devices(new)',
    deleteLightGroup: 'Disband light group',
    linkDevice: 'Link devices',
    noSuppurtedLinkageDevice: 'No devices available for linking now',
    noSuppurtedLinkageTip: '1.Please make sure the device to link with has been added to the app, and is assigned to the preferred room.\n2.Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    supportedLinkageDevices: 'Can be linked with the following devices',
    linkageDistanceTip: 'Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    linkageRemoveTip: 'If the linked Bluetooth device needs to be changed, please remove link first.',
    link: 'Link',
    removeLink: 'Remove link',
    linkFail: 'Couldn\'t link',
    removeLinkFail: 'Couldn\'t remove the link',
    linkConfirm: 'Link with this device now?',
    removeLinkConfirm: 'Remove link now?',
    linking: 'Linking…',
    pluginVersion: 'Plugin version number',
    helpAndFeedback: '도움말 & 피드백'
  },
  ru: {
    setting: 'Настройки',
    featureSetting: 'Настройки устройств',
    commonSetting: 'Общие настройки',
    name: 'Имя устройства',
    location: 'Управлять местами',
    memberSet: 'Настройка кнопок',
    share: 'Поделиться устройством',
    btGateway: 'BLE шлюз',
    voiceAuth: 'Голосовая авторизация',
    ifttt: 'Автоматизация',
    firmwareUpgrade: 'Проверить наличие обновлений',
    more: 'Дополнительные настройки',
    help: 'Справка',
    legalInfo: 'Легальная информация',
    deleteDevice: 'Удалить устройство',
    autoUpgrade: 'Автоматическое обновление встроенного ПО',
    checkUpgrade: 'Проверить наличие обновлений',
    security: 'Параметры безопасности',
    networkInfo: 'Информация о сети',
    feedback: 'Отзыв',
    timezone: 'Часовой пояс устройства',
    addToDesktop: 'Добавить на главный экран',
    // MHDatePicker
    cancel: 'Cancel',
    ok: 'Confirm',
    am: 'AM',
    pm: 'PM',
    months: 'months',
    days: 'days',
    hours: 'hours',
    minutes: 'minutes',
    seconds: 'seconds',
    month: 'month',
    day: 'day',
    hour: 'hour',
    minute: 'minute',
    second: 'second',
    yearUnit: '',
    monthUnit: '',
    dayUnit: '',
    hourUnit: '',
    minuteUnit: '',
    secondUnit: '',
    dateSubTitle: '{0}-{1}-{2}', // 2019-06-03
    time24SubTitle: '{0}:{1}', // 11:43
    time12SubTitle: '{1}:{2} {0}', // 11:43 am
    singleSubTitle: '{0} {1}', // 1 hour | 2 hours
    // 升级相关
    firmwareUpgradeExit: 'Выход',
    firmwareUpgradeUpdate: 'Обновление',
    firmwareUpgradeLook: 'Посмотреть',
    firmwareUpgradeForceUpdate: 'Текущая версия ПО устарела, некоторые возможности могут быть недоступны. Обновите до последней версии ПО.',
    firmwareUpgradeForceUpdating: 'Устройство обновляется, попробуйте позже',
    firmwareUpgradeNew_pre: 'Доступно обновление ПО ',
    firmwareUpgradeNew_sub: ', обновить сейчас?',
    handling: 'Загрузка...',
    error: 'Попробовать снова',
    createLightGroup: 'Create light group(new)',
    manageLightGroup: 'Manage devices(new)',
    deleteLightGroup: 'Disband light group',
    linkDevice: 'Link devices',
    noSuppurtedLinkageDevice: 'No devices available for linking now',
    noSuppurtedLinkageTip: '1.Please make sure the device to link with has been added to the app, and is assigned to the preferred room.\n2.Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    supportedLinkageDevices: 'Can be linked with the following devices',
    linkageDistanceTip: 'Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    linkageRemoveTip: 'If the linked Bluetooth device needs to be changed, please remove link first.',
    link: 'Link',
    removeLink: 'Remove link',
    linkFail: 'Couldn\'t link',
    removeLinkFail: 'Couldn\'t remove the link',
    linkConfirm: 'Link with this device now?',
    removeLinkConfirm: 'Remove link now?',
    linking: 'Linking…',
    pluginVersion: 'Plugin version number',
    helpAndFeedback: 'Справка и обратная связь'
  },
  es: {
    setting: 'Ajustes',
    featureSetting: 'Ajustes de dispositivo',
    commonSetting: 'Ajustes generales',
    name: 'Nombre del dispositivo',
    location: 'Gestionar ubicaciones',
    memberSet: 'Ajustes de los botones',
    share: 'Compartir dispositivo',
    btGateway: 'Entrada BLE',
    voiceAuth: 'Autorización de voz',
    ifttt: 'Automatización',
    firmwareUpgrade: 'Actualizaciones de firmware',
    more: 'Ajustes adicionales',
    help: 'Ayuda',
    legalInfo: 'Información legal',
    deleteDevice: 'Eliminar dispositivo',
    autoUpgrade: 'Actualizar automáticamente el firmware',
    checkUpgrade: 'Buscar actualizaciones de firmware',
    security: 'Ajustes de seguridad',
    networkInfo: 'Información de red',
    feedback: 'Comentario',
    timezone: 'Zona horaria del dispositivo',
    addToDesktop: 'Añadir a la pantalla de Inicio',
    // MHDatePicker
    cancel: 'Cancel',
    ok: 'Confirm',
    am: 'AM',
    pm: 'PM',
    months: 'months',
    days: 'days',
    hours: 'hours',
    minutes: 'minutes',
    seconds: 'seconds',
    month: 'month',
    day: 'day',
    hour: 'hour',
    minute: 'minute',
    second: 'second',
    yearUnit: '',
    monthUnit: '',
    dayUnit: '',
    hourUnit: '',
    minuteUnit: '',
    secondUnit: '',
    dateSubTitle: '{0}-{1}-{2}', // 2019-06-03
    time24SubTitle: '{0}:{1}', // 11:43
    time12SubTitle: '{1}:{2} {0}', // 11:43 am
    singleSubTitle: '{0} {1}', // 1 hour | 2 hours
    // 升级相关
    firmwareUpgradeExit: 'Salir',
    firmwareUpgradeUpdate: 'Actualizar',
    firmwareUpgradeLook: 'Echa un vistazo',
    firmwareUpgradeForceUpdate: 'La versión de firmware actual es demasiado antigua, puede que algunas características no funcionen correctamente. Actualiza a la última versión para una mejor experiencia.',
    firmwareUpgradeForceUpdating: 'Tu dispositivo se está actualizando, inténtalo más tarde',
    firmwareUpgradeNew_pre: 'Actualización ',
    firmwareUpgradeNew_sub: ' de firmware disponible, ¿actualizar ahora?',
    handling: 'Ejecutándose...',
    error: 'Reintentar',
    createLightGroup: 'Create light group(new)',
    manageLightGroup: 'Manage devices(new)',
    deleteLightGroup: 'Disband light group',
    linkDevice: 'Link devices',
    noSuppurtedLinkageDevice: 'No devices available for linking now',
    noSuppurtedLinkageTip: '1.Please make sure the device to link with has been added to the app, and is assigned to the preferred room.\n2.Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    supportedLinkageDevices: 'Can be linked with the following devices',
    linkageDistanceTip: 'Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    linkageRemoveTip: 'If the linked Bluetooth device needs to be changed, please remove link first.',
    link: 'Link',
    removeLink: 'Remove link',
    linkFail: 'Couldn\'t link',
    removeLinkFail: 'Couldn\'t remove the link',
    linkConfirm: 'Link with this device now?',
    removeLinkConfirm: 'Remove link now?',
    linking: 'Linking…',
    pluginVersion: 'Plugin version number',
    helpAndFeedback: 'Ayuda y Comentarios'
  },
  fr: {
    setting: 'Paramètres',
    featureSetting: 'Paramètres des appareils',
    commonSetting: 'Paramètres généraux',
    name: "Nom de l'appareil",
    location: 'Gérer les emplacements',
    memberSet: 'Paramètres des boutons',
    share: "Partager l'appareil",
    btGateway: 'Passerelle BLE',
    voiceAuth: 'Autorisation vocale',
    ifttt: 'Automatisation',
    firmwareUpgrade: 'Les mises à jour du micrologiciel',
    more: 'Paramètres supplémentaires',
    help: 'Aide',
    legalInfo: 'Information légale',
    deleteDevice: "Supprimer l'appareil",
    autoUpgrade: 'Mise à jour automatique du firmware',
    checkUpgrade: 'Vérifier les mises à jour du micrologiciel',
    security: 'Paramètres de sécurité',
    networkInfo: 'Informations sur le réseau',
    feedback: 'Commentaire',
    timezone: 'Fuseau horaire de l’appareil',
    addToDesktop: "Ajouter à l'écran d'accueil'",
    // MHDatePicker
    cancel: 'Cancel',
    ok: 'Confirm',
    am: 'AM',
    pm: 'PM',
    months: 'months',
    days: 'days',
    hours: 'hours',
    minutes: 'minutes',
    seconds: 'seconds',
    month: 'month',
    day: 'day',
    hour: 'hour',
    minute: 'minute',
    second: 'second',
    yearUnit: '',
    monthUnit: '',
    dayUnit: '',
    hourUnit: '',
    minuteUnit: '',
    secondUnit: '',
    dateSubTitle: '{0}-{1}-{2}', // 2019-06-03
    time24SubTitle: '{0}:{1}', // 11:43
    time12SubTitle: '{1}:{2} {0}', // 11:43 am
    singleSubTitle: '{0} {1}', // 1 hour | 2 hours
    // 升级相关
    firmwareUpgradeExit: 'Quitter',
    firmwareUpgradeUpdate: 'Mettre à jour',
    firmwareUpgradeLook: 'Jeter un coup d\'œil',
    firmwareUpgradeForceUpdate: 'La version actuelle du micrologiciel est trop ancienne. Certaines fonctionnalités peuvent ne pas fonctionner correctement. Mettre à jour la dernière version pour une meilleure expérience',
    firmwareUpgradeForceUpdating: 'Votre appareil est en cours de mise à jour. Réessayez plus tard',
    firmwareUpgradeNew_pre: 'Mise à jour du micrologiciel ',
    firmwareUpgradeNew_sub: ' disponible. Mettre à jour maintenant ?',
    handling: 'En cours d’exécution…',
    error: 'Réessayer',
    createLightGroup: 'Create light group(new)',
    manageLightGroup: 'Manage devices(new)',
    deleteLightGroup: 'Disband light group',
    linkDevice: 'Link devices',
    noSuppurtedLinkageDevice: 'No devices available for linking now',
    noSuppurtedLinkageTip: '1.Please make sure the device to link with has been added to the app, and is assigned to the preferred room.\n2.Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    supportedLinkageDevices: 'Can be linked with the following devices',
    linkageDistanceTip: 'Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    linkageRemoveTip: 'If the linked Bluetooth device needs to be changed, please remove link first.',
    link: 'Link',
    removeLink: 'Remove link',
    linkFail: 'Couldn\'t link',
    removeLinkFail: 'Couldn\'t remove the link',
    linkConfirm: 'Link with this device now?',
    removeLinkConfirm: 'Remove link now?',
    linking: 'Linking…',
    pluginVersion: 'Plugin version number',
    helpAndFeedback: 'Aide et commentaires'
  },
  it: {
    setting: 'Impostazioni',
    featureSetting: 'Impostazioni dispositivo',
    commonSetting: 'Impostazioni generali',
    name: 'Nome dispositivo',
    location: 'Gestisci posizioni',
    memberSet: 'Impostazioni pulsante',
    share: 'Condividi dispositivo',
    btGateway: 'Gateway BLE',
    voiceAuth: 'Autorizzazione vocale',
    ifttt: 'Automazione',
    firmwareUpgrade: 'Aggiornamenti firmware',
    more: 'Impostazioni aggiuntive',
    help: 'Guida',
    legalInfo: 'Informazioni legali',
    deleteDevice: 'Rimuovi dispositivo',
    autoUpgrade: 'Aggiorna automaticamente il firmware',
    checkUpgrade: 'Controlla aggiornamenti firmware',
    security: 'Impostazioni di sicurezza',
    networkInfo: 'Informazioni di rete',
    feedback: 'Feedback',
    timezone: 'Fuso orario del dispositivo',
    addToDesktop: 'Aggiungi a schermata iniziale',
    // MHDatePicker
    cancel: 'Cancel',
    ok: 'Confirm',
    am: 'AM',
    pm: 'PM',
    months: 'months',
    days: 'days',
    hours: 'hours',
    minutes: 'minutes',
    seconds: 'seconds',
    month: 'month',
    day: 'day',
    hour: 'hour',
    minute: 'minute',
    second: 'second',
    yearUnit: '',
    monthUnit: '',
    dayUnit: '',
    hourUnit: '',
    minuteUnit: '',
    secondUnit: '',
    dateSubTitle: '{0}-{1}-{2}', // 2019-06-03
    time24SubTitle: '{0}:{1}', // 11:43
    time12SubTitle: '{1}:{2} {0}', // 11:43 am
    singleSubTitle: '{0} {1}', // 1 hour | 2 hours
    // 升级相关
    firmwareUpgradeExit: 'Esci',
    firmwareUpgradeUpdate: 'Aggiorna',
    firmwareUpgradeLook: 'Guarda',
    firmwareUpgradeForceUpdate: 'La versione firmware in uso è obsoleta. Alcune funzioni potrebbero non funzionare correttamente. Esegui l\'aggiornamento alla versione più recente per usufruire di prestazioni migliori.',
    firmwareUpgradeForceUpdating: 'Il dispositivo è in fase di aggiornamento. Riprova più tardi',
    firmwareUpgradeNew_pre: 'Aggiornamento firmware ',
    firmwareUpgradeNew_sub: ' disponibile. Aggiornare adesso?',
    handling: 'In esecuzione…',
    error: 'Riprova',
    createLightGroup: 'Create light group(new)',
    manageLightGroup: 'Manage devices(new)',
    deleteLightGroup: 'Disband light group',
    linkDevice: 'Link devices',
    noSuppurtedLinkageDevice: 'No devices available for linking now',
    noSuppurtedLinkageTip: '1.Please make sure the device to link with has been added to the app, and is assigned to the preferred room.\n2.Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    supportedLinkageDevices: 'Can be linked with the following devices',
    linkageDistanceTip: 'Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    linkageRemoveTip: 'If the linked Bluetooth device needs to be changed, please remove link first.',
    link: 'Link',
    removeLink: 'Remove link',
    linkFail: 'Couldn\'t link',
    removeLinkFail: 'Couldn\'t remove the link',
    linkConfirm: 'Link with this device now?',
    removeLinkConfirm: 'Remove link now?',
    linking: 'Linking…',
    pluginVersion: 'Plugin version number',
    helpAndFeedback: 'Guida e feedback'
  },
  de: {
    setting: 'Einstellungen',
    featureSetting: 'Geräteeinstellungen',
    commonSetting: 'Allgemeine einstellungen',
    name: 'Gerätename',
    location: 'Standorte verwalten',
    memberSet: 'Schaltflächen-einstellungen',
    share: 'Gerät teilen',
    btGateway: 'BLE-Gateway',
    voiceAuth: 'Identitätsnachweis über die Stimme',
    ifttt: 'Automatisierung',
    firmwareUpgrade: 'Firmware-Aktualisierungen',
    more: 'Zusätzliche Einstellungen',
    help: 'Hilfe',
    legalInfo: 'Rechtsinformation',
    deleteDevice: 'Geräte entfernen',
    autoUpgrade: 'Firmware automatisch aktualisieren',
    checkUpgrade: 'Nach Firmware-Aktualisierungen suchen',
    security: 'Sicherheitseinstellungen',
    networkInfo: 'Netzwerk-Info',
    feedback: 'Feedback',
    timezone: 'Gerätezeitzone',
    addToDesktop: 'Zum Startbildschirm hinzufügen',
    // MHDatePicker
    cancel: 'Cancel',
    ok: 'Confirm',
    am: 'AM',
    pm: 'PM',
    months: 'months',
    days: 'days',
    hours: 'hours',
    minutes: 'minutes',
    seconds: 'seconds',
    month: 'month',
    day: 'day',
    hour: 'hour',
    minute: 'minute',
    second: 'second',
    yearUnit: '',
    monthUnit: '',
    dayUnit: '',
    hourUnit: '',
    minuteUnit: '',
    secondUnit: '',
    dateSubTitle: '{0}-{1}-{2}', // 2019-06-03
    time24SubTitle: '{0}:{1}', // 11:43
    time12SubTitle: '{1}:{2} {0}', // 11:43 am
    singleSubTitle: '{0} {1}', // 1 hour | 2 hours
    // 升级相关
    firmwareUpgradeExit: 'Beenden',
    firmwareUpgradeUpdate: 'Aktualisieren',
    firmwareUpgradeLook: 'Ansehen',
    firmwareUpgradeForceUpdate: 'Aktuelle Firmware-Version ist zu alt, einige Funktionen arbeiten möglicherweise nicht korrekt. Aktualisieren Sie auf die neueste Version, um eine verbesserte Funktionsausführung zu erzielen.',
    firmwareUpgradeForceUpdating: 'Ihr Gerät wird aktualisiert, versuchen Sie es später erneut',
    firmwareUpgradeNew_pre: 'Firmware-Aktualisierung ',
    firmwareUpgradeNew_sub: ' verfügbar, jetzt aktualisieren?',
    handling: 'Wird ausgeführt...',
    error: 'Erneut versuchen',
    createLightGroup: 'Create light group(new)',
    manageLightGroup: 'Manage devices(new)',
    deleteLightGroup: 'Disband light group',
    linkDevice: 'Link devices',
    noSuppurtedLinkageDevice: 'No devices available for linking now',
    noSuppurtedLinkageTip: '1.Please make sure the device to link with has been added to the app, and is assigned to the preferred room.\n2.Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    supportedLinkageDevices: 'Can be linked with the following devices',
    linkageDistanceTip: 'Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    linkageRemoveTip: 'If the linked Bluetooth device needs to be changed, please remove link first.',
    link: 'Link',
    removeLink: 'Remove link',
    linkFail: 'Couldn\'t link',
    removeLinkFail: 'Couldn\'t remove the link',
    linkConfirm: 'Link with this device now?',
    removeLinkConfirm: 'Remove link now?',
    linking: 'Linking…',
    pluginVersion: 'Plugin version number',
    helpAndFeedback: 'Hilfe und Feedback'
  },
  id: {
    setting: 'Pengaturan',
    featureSetting: 'Pengaturan perangkat',
    commonSetting: 'Pengaturan umum',
    name: 'Nama perangkat',
    location: 'Kelola lokasi',
    memberSet: 'Pengaturan tombol',
    share: 'Bagikan perangkat',
    btGateway: 'Gerbang BLE',
    voiceAuth: 'Otorisasi suara',
    ifttt: 'Otomatisasi',
    firmwareUpgrade: 'Pembaruan firmware',
    more: 'Pengaturan tambahan',
    help: 'Bantuan',
    legalInfo: 'Informasi hukum',
    deleteDevice: 'Hapus perangkat',
    autoUpgrade: 'Perbarui firmware secara otomatis',
    checkUpgrade: 'Periksa pembaruan firmware',
    security: 'Pengaturan keamanan',
    networkInfo: 'Pengaturan jaringan',
    feedback: 'Umpan balik',
    timezone: 'Zona waktu perangkat',
    addToDesktop: 'Tambahkan ke layar Beranda',
    // MHDatePicker
    cancel: 'Cancel',
    ok: 'Confirm',
    am: 'AM',
    pm: 'PM',
    months: 'months',
    days: 'days',
    hours: 'hours',
    minutes: 'minutes',
    seconds: 'seconds',
    month: 'month',
    day: 'day',
    hour: 'hour',
    minute: 'minute',
    second: 'second',
    yearUnit: '',
    monthUnit: '',
    dayUnit: '',
    hourUnit: '',
    minuteUnit: '',
    secondUnit: '',
    dateSubTitle: '{0}-{1}-{2}', // 2019-06-03
    time24SubTitle: '{0}:{1}', // 11:43
    time12SubTitle: '{1}:{2} {0}', // 11:43 am
    singleSubTitle: '{0} {1}', // 1 hour | 2 hours
    // 升级相关
    firmwareUpgradeExit: 'Keluar',
    firmwareUpgradeUpdate: 'Perbarui',
    firmwareUpgradeLook: 'Lihat',
    firmwareUpgradeForceUpdate: 'Versi firmware saat ini sudah terlalu lama. Beberapa fitur mungkin tidak berfungsi dengan benar. Perbarui ke versi terbaru untuk menikmati pengalaman yang lebih baik.',
    firmwareUpgradeForceUpdating: 'Perangkat sedang diperbarui, coba lagi nanti',
    firmwareUpgradeNew_pre: 'Pembaruan firmware ',
    firmwareUpgradeNew_sub: ' tersedia, perbarui sekarang?',
    handling: 'Menjalankan...',
    error: 'Coba lagi',
    createLightGroup: 'Create light group(new)',
    manageLightGroup: 'Manage devices(new)',
    deleteLightGroup: 'Disband light group',
    linkDevice: 'Link devices',
    noSuppurtedLinkageDevice: 'No devices available for linking now',
    noSuppurtedLinkageTip: '1.Please make sure the device to link with has been added to the app, and is assigned to the preferred room.\n2.Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    supportedLinkageDevices: 'Can be linked with the following devices',
    linkageDistanceTip: 'Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    linkageRemoveTip: 'If the linked Bluetooth device needs to be changed, please remove link first.',
    link: 'Link',
    removeLink: 'Remove link',
    linkFail: 'Couldn\'t link',
    removeLinkFail: 'Couldn\'t remove the link',
    linkConfirm: 'Link with this device now?',
    removeLinkConfirm: 'Remove link now?',
    linking: 'Linking…',
    pluginVersion: 'Plugin version number',
    helpAndFeedback: 'Bantuan & Umpan Balik'
  },
  pl: {
    setting: 'Ustawienia',
    featureSetting: 'Ustawienia urządzeń',
    commonSetting: 'Ustawienia ogólne',
    name: 'Nazwa urządzenia',
    location: 'Zarządzaj lokalizacją',
    memberSet: 'Ustawienia przycisku',
    share: 'Udostępnij urządzenie',
    btGateway: 'Bramka BLE',
    voiceAuth: 'Autoryzacja głosu',
    ifttt: 'Automatyzacja',
    firmwareUpgrade: 'Aktualizacje oprogramowania sprzętowe',
    more: 'Dodatkowe ustawienia',
    help: 'Pomoc',
    legalInfo: 'Informacje prawne',
    deleteDevice: 'Usuń urządzenie',
    autoUpgrade: 'Automatyczna aktualizacja oprogramowania układowego',
    checkUpgrade: 'Sprawdź aktualizacje oprogramowania sprzętowe',
    security: 'Ustawienia bezpieczeństwa',
    networkInfo: 'Informacje o sieci',
    feedback: 'Informacje zwrotne',
    timezone: 'Strefa czasowa urządzenia',
    addToDesktop: 'Dodaj do ekranu głównego',
    // MHDatePicker
    cancel: 'Cancel',
    ok: 'Confirm',
    am: 'AM',
    pm: 'PM',
    months: 'months',
    days: 'days',
    hours: 'hours',
    minutes: 'minutes',
    seconds: 'seconds',
    month: 'month',
    day: 'day',
    hour: 'hour',
    minute: 'minute',
    second: 'second',
    yearUnit: '',
    monthUnit: '',
    dayUnit: '',
    hourUnit: '',
    minuteUnit: '',
    secondUnit: '',
    dateSubTitle: '{0}-{1}-{2}', // 2019-06-03
    time24SubTitle: '{0}:{1}', // 11:43
    time12SubTitle: '{1}:{2} {0}', // 11:43 am
    singleSubTitle: '{0} {1}', // 1 hour | 2 hours
    // 升级相关
    firmwareUpgradeExit: 'Wyjdź',
    firmwareUpgradeUpdate: 'Aktualizuj',
    firmwareUpgradeLook: 'Przegląd',
    firmwareUpgradeForceUpdate: 'Aktualna wersja oprogramowania sprzętowego jest zbyt stara, aby niektóre funkcje działały poprawnie. Zaktualizuj do najnowszej wersji, aby poprawić użytkowanie.',
    firmwareUpgradeForceUpdating: 'Urządzenie jest aktualizowane, spróbuj ponownie później.',
    firmwareUpgradeNew_pre: 'Dostępna jest aktualizacja oprogramowania sprzętowego dla ',
    firmwareUpgradeNew_sub: '. Zaktualizować teraz?',
    handling: 'Pracuje…',
    error: 'Spróbuj ponownie',
    createLightGroup: 'Create light group(new)',
    manageLightGroup: 'Manage devices(new)',
    deleteLightGroup: 'Disband light group',
    linkDevice: 'Link devices',
    noSuppurtedLinkageDevice: 'No devices available for linking now',
    noSuppurtedLinkageTip: '1.Please make sure the device to link with has been added to the app, and is assigned to the preferred room.\n2.Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    supportedLinkageDevices: 'Can be linked with the following devices',
    linkageDistanceTip: 'Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    linkageRemoveTip: 'If the linked Bluetooth device needs to be changed, please remove link first.',
    link: 'Link',
    removeLink: 'Remove link',
    linkFail: 'Couldn\'t link',
    removeLinkFail: 'Couldn\'t remove the link',
    linkConfirm: 'Link with this device now?',
    removeLinkConfirm: 'Remove link now?',
    linking: 'Linking…',
    pluginVersion: 'Plugin version number',
    helpAndFeedback: 'Pomoc i informacje zwrotne'
  },
  vi: {
    setting: 'Cài đặt',
    featureSetting: 'Cài đặt thiết bị',
    commonSetting: 'Cài đặt chung',
    name: 'Tên thiết bị',
    location: 'Quản lý các vị trí',
    memberSet: 'Cài đặt nút',
    share: 'Chia sẻ thiết bị',
    btGateway: 'Cổng BLE',
    voiceAuth: 'Cấp quyền bằng giọng nói',
    ifttt: 'Tự động',
    firmwareUpgrade: 'Kiểm tra bản cập nhật chương trình cơ sở',
    more: 'Cài đặt khác',
    help: 'Trợ giúp',
    legalInfo: 'Thông tin hợp pháp',
    deleteDevice: 'Xóa thiết bị',
    autoUpgrade: 'Tự động cập nhật chương trình cơ sở',
    checkUpgrade: 'Kiểm tra bản cập nhật chương trình cơ sở',
    security: 'Cài đặt bảo mật',
    networkInfo: 'Thiết lập mạng',
    feedback: 'Phản hồi',
    timezone: 'Múi giờ thiết bị',
    addToDesktop: 'Thêm vào Màn hình chính',
    // MHDatePicker
    cancel: 'Cancel',
    ok: 'Confirm',
    am: 'AM',
    pm: 'PM',
    months: 'months',
    days: 'days',
    hours: 'hours',
    minutes: 'minutes',
    seconds: 'seconds',
    month: 'month',
    day: 'day',
    hour: 'hour',
    minute: 'minute',
    second: 'second',
    yearUnit: '',
    monthUnit: '',
    dayUnit: '',
    hourUnit: '',
    minuteUnit: '',
    secondUnit: '',
    dateSubTitle: '{0}-{1}-{2}', // 2019-06-03
    time24SubTitle: '{0}:{1}', // 11:43
    time12SubTitle: '{1}:{2} {0}', // 11:43 am
    singleSubTitle: '{0} {1}', // 1 hour | 2 hours
    // 升级相关
    firmwareUpgradeExit: 'Thoát',
    firmwareUpgradeUpdate: 'Cập nhật',
    firmwareUpgradeLook: 'Xem xét',
    firmwareUpgradeForceUpdate: 'Phiên bản chương trình cơ sở hiện tại quá cũ, một số tính năng có thể không hoạt động bình thường. Cập nhật lên phiên bản mới nhất để có trải nghiệm tốt hơn.',
    firmwareUpgradeForceUpdating: 'Thiết bị của bạn đang cập nhật, hãy thử lại sau',
    firmwareUpgradeNew_pre: 'Đã có bản cập nhật chương trình cơ sở ',
    firmwareUpgradeNew_sub: ', cập nhật ngay bây giờ?',
    handling: 'Đang thực hiện',
    error: 'Thử lại',
    createLightGroup: 'Create light group(new)',
    manageLightGroup: 'Manage devices(new)',
    deleteLightGroup: 'Disband light group',
    linkDevice: 'Link devices',
    noSuppurtedLinkageDevice: 'No devices available for linking now',
    noSuppurtedLinkageTip: '1.Please make sure the device to link with has been added to the app, and is assigned to the preferred room.\n2.Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    supportedLinkageDevices: 'Can be linked with the following devices',
    linkageDistanceTip: 'Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    linkageRemoveTip: 'If the linked Bluetooth device needs to be changed, please remove link first.',
    link: 'Link',
    removeLink: 'Remove link',
    linkFail: 'Couldn\'t link',
    removeLinkFail: 'Couldn\'t remove the link',
    linkConfirm: 'Link with this device now?',
    removeLinkConfirm: 'Remove link now?',
    linking: 'Linking…',
    pluginVersion: 'Plugin version number',
    helpAndFeedback: 'Trợ giúp và phản hồi'
  },
  ja: {
    setting: '設定',
    featureSetting: 'デバイス設定',
    commonSetting: '全般設定',
    name: 'デバイス名',
    location: '位置を管理する',
    memberSet: 'ボタンの設定',
    share: 'デバイスを共有する',
    btGateway: 'BLE ゲートウェイ',
    voiceAuth: '音声承認',
    ifttt: '自動化',
    firmwareUpgrade: 'ファームウェア更新する',
    more: '詳細設定',
    help: 'ヘルプ',
    legalInfo: '法律情報',
    deleteDevice: 'デバイスを削除する',
    autoUpgrade: 'ファームウェアの自動アップグレード',
    checkUpgrade: 'ファームウェア更新プログラムの有無を確認する',
    security: 'セキュリティ設定',
    networkInfo: 'ネットワーク設定',
    feedback: 'フィードバック',
    timezone: 'デバイスタイムゾーン',
    addToDesktop: 'ホーム画面に追加する',
    // MHDatePicker
    cancel: 'Cancel',
    ok: 'Confirm',
    am: 'AM',
    pm: 'PM',
    months: 'months',
    days: 'days',
    hours: 'hours',
    minutes: 'minutes',
    seconds: 'seconds',
    month: 'month',
    day: 'day',
    hour: 'hour',
    minute: 'minute',
    second: 'second',
    yearUnit: '',
    monthUnit: '',
    dayUnit: '',
    hourUnit: '',
    minuteUnit: '',
    secondUnit: '',
    dateSubTitle: '{0}-{1}-{2}', // 2019-06-03
    time24SubTitle: '{0}:{1}', // 11:43
    time12SubTitle: '{1}:{2} {0}', // 11:43 am
    singleSubTitle: '{0} {1}', // 1 hour | 2 hours
    // 升级相关
    firmwareUpgradeExit: '終了',
    firmwareUpgradeUpdate: '更新',
    firmwareUpgradeLook: '調べる',
    firmwareUpgradeForceUpdate: '現在のファームウェア バージョンは古すぎます。一部の機能が正しく動作しないおそれがあります。ユーザー エクスペリエンスを高めるため、最新バージョンに更新してください。',
    firmwareUpgradeForceUpdating: 'デバイスは更新中です。後で再試行してください',
    firmwareUpgradeNew_pre: 'ファームウェア更新プログラム ',
    firmwareUpgradeNew_sub: ' が公開されています。今すぐ更新しますか?',
    handling: '実行中',
    error: '再試行する',
    createLightGroup: 'Create light group(new)',
    manageLightGroup: 'Manage devices(new)',
    deleteLightGroup: 'Disband light group',
    linkDevice: 'Link devices',
    noSuppurtedLinkageDevice: 'No devices available for linking now',
    noSuppurtedLinkageTip: '1.Please make sure the device to link with has been added to the app, and is assigned to the preferred room.\n2.Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    supportedLinkageDevices: 'Can be linked with the following devices',
    linkageDistanceTip: 'Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    linkageRemoveTip: 'If the linked Bluetooth device needs to be changed, please remove link first.',
    link: 'Link',
    removeLink: 'Remove link',
    linkFail: 'Couldn\'t link',
    removeLinkFail: 'Couldn\'t remove the link',
    linkConfirm: 'Link with this device now?',
    removeLinkConfirm: 'Remove link now?',
    linking: 'Linking…',
    pluginVersion: 'Plugin version number',
    helpAndFeedback: 'ヘルプおよびフィードバック'
  },
  th: {
    setting: 'การตั้งค่า',
    featureSetting: 'การตั้งค่าอุปกรณ์',
    commonSetting: 'การตั้งค่าทั่วไป',
    name: 'ชื่ออุปกรณ์',
    location: 'จัดการตำแหน่งที่ตั้ง',
    memberSet: 'การตั้งค่าปุ่ม',
    share: 'แชร์อุปกรณ์',
    btGateway: 'เกตเวย์ BLE',
    voiceAuth: 'การอนุญาตด้วยเสียง',
    ifttt: 'ระบบอัตโนมัติ',
    firmwareUpgrade: 'ตรวจสอบหาการอัปเดตเฟิร์มแวร์',
    more: 'การตั้งค่าเพิ่มเติม',
    help: 'ความช่วยเหลือ',
    legalInfo: 'ข้อมูลทางกฎหมาย',
    deleteDevice: 'ลบอุปกรณ์ออก',
    autoUpgrade: 'อัปเดตเฟิร์มแวร์โดยอัตโนมัติ',
    checkUpgrade: 'ตรวจสอบหาการอัปเดตเฟิร์มแวร์',
    security: 'การตั้งค่าความปลอดภัย',
    networkInfo: 'การตั้งค่าเครือข่าย',
    feedback: 'คำติชม',
    timezone: 'โซนเวลาของอุปกรณ์',
    addToDesktop: 'เพิ่มไปยังหน้าโฮม',
    // MHDatePicker
    cancel: 'Cancel',
    ok: 'Confirm',
    am: 'AM',
    pm: 'PM',
    months: 'months',
    days: 'days',
    hours: 'hours',
    minutes: 'minutes',
    seconds: 'seconds',
    month: 'month',
    day: 'day',
    hour: 'hour',
    minute: 'minute',
    second: 'second',
    yearUnit: '',
    monthUnit: '',
    dayUnit: '',
    hourUnit: '',
    minuteUnit: '',
    secondUnit: '',
    dateSubTitle: '{0}-{1}-{2}', // 2019-06-03
    time24SubTitle: '{0}:{1}', // 11:43
    time12SubTitle: '{1}:{2} {0}', // 11:43 am
    singleSubTitle: '{0} {1}', // 1 hour | 2 hours
    // 升级相关
    firmwareUpgradeExit: 'ออก',
    firmwareUpgradeUpdate: 'อัปเดต',
    firmwareUpgradeLook: 'ลองดู',
    firmwareUpgradeForceUpdate: 'เวอร์ชั่นเฟิร์มแวร์ปัจจุบันเก่าไป ฟีเจอร์บางอย่างอาจทำงานไม่ถูกต้อง อัปเดตเป็นเวอร์ชั่นล่าสุดเพื่อประสบการณ์การใช้งานที่ดีขึ้น',
    firmwareUpgradeForceUpdating: 'อุปกรณ์กำลังอัปเดต ลองอีกครั้งในภายหลัง',
    firmwareUpgradeNew_pre: 'เฟิร์มแวร์อัปเดต ',
    firmwareUpgradeNew_sub: ' ใช้ได้แล้ว อัปเดตตอนนี้หรือไม่',
    handling: 'ในการดำเนินการ',
    error: 'ลองอีกครั้ง',
    createLightGroup: 'Create light group(new)',
    manageLightGroup: 'Manage devices(new)',
    deleteLightGroup: 'Disband light group',
    linkDevice: 'Link devices',
    noSuppurtedLinkageDevice: 'No devices available for linking now',
    noSuppurtedLinkageTip: '1.Please make sure the device to link with has been added to the app, and is assigned to the preferred room.\n2.Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    supportedLinkageDevices: 'Can be linked with the following devices',
    linkageDistanceTip: 'Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    linkageRemoveTip: 'If the linked Bluetooth device needs to be changed, please remove link first.',
    link: 'Link',
    removeLink: 'Remove link',
    linkFail: 'Couldn\'t link',
    removeLinkFail: 'Couldn\'t remove the link',
    linkConfirm: 'Link with this device now?',
    removeLinkConfirm: 'Remove link now?',
    linking: 'Linking…',
    pluginVersion: 'Plugin version number',
    helpAndFeedback: 'ความช่วยเหลือและคำติชม'
  },
  tr: {
    setting: 'Ayarlar',
    featureSetting: 'Cihaz ayarları',
    commonSetting: 'Genel ayarlar',
    name: 'Cihaz adı',
    location: 'Konum yönetimi',
    memberSet: 'Tuş ayarları',
    share: 'Cihazı paylaş',
    btGateway: 'BLE ağ geçidi',
    voiceAuth: 'Sesli yetkilendirme',
    ifttt: 'Otomasyon',
    firmwareUpgrade: 'Cihaz güncelleştirmeleri',
    more: 'Ek ayarlar',
    help: 'Yardım',
    legalInfo: 'Yasal bilgi',
    deleteDevice: 'Cihazı sil',
    autoUpgrade: 'Ürün yazılımını otomatik olarak güncelle',
    checkUpgrade: 'Üretici yazılımı güncelleştirmelerini denetle',
    security: 'Güvenlik ayarları',
    networkInfo: 'Ağ bilgileri',
    feedback: 'Geri bildirimlerim',
    timezone: 'Cihazın saat dilimi',
    addToDesktop: 'Ana ekrana ekleyin',
    // MHDatePicker
    cancel: 'Cancel',
    ok: 'Confirm',
    am: 'AM',
    pm: 'PM',
    months: 'months',
    days: 'days',
    hours: 'hours',
    minutes: 'minutes',
    seconds: 'seconds',
    month: 'month',
    day: 'day',
    hour: 'hour',
    minute: 'minute',
    second: 'second',
    yearUnit: '',
    monthUnit: '',
    dayUnit: '',
    hourUnit: '',
    minuteUnit: '',
    secondUnit: '',
    dateSubTitle: '{0}-{1}-{2}', // 2019-06-03
    time24SubTitle: '{0}:{1}', // 11:43
    time12SubTitle: '{1}:{2} {0}', // 11:43 am
    singleSubTitle: '{0} {1}', // 1 hour | 2 hours
    // 升级相关
    firmwareUpgradeExit: 'Çıkış',
    firmwareUpgradeUpdate: 'Şimdi güncelleştir',
    firmwareUpgradeLook: 'Şimdi göz atın',
    firmwareUpgradeForceUpdate: 'Mevcut ürün yazılımı bazı özellikleri çalıştırmak için çok eski olabilir. Daha iyi bir deneyim için en son sürüme güncelleyin.',
    firmwareUpgradeForceUpdating: 'Cihazınız güncelleştiriliyor, daha sonra yeniden deneyin',
    firmwareUpgradeNew_pre: 'Üretici yazılımı güncelleştirmesi',
    firmwareUpgradeNew_sub: 'kullanılabilir. Şimdi güncelleştir',
    handling: 'İşleniyor…',
    error: 'Kon niet werken, probeer het later opnieuw.',
    createLightGroup: 'Create light group(new)',
    manageLightGroup: 'Manage devices(new)',
    deleteLightGroup: 'Disband light group',
    linkDevice: 'Link devices',
    noSuppurtedLinkageDevice: 'No devices available for linking now',
    noSuppurtedLinkageTip: '1.Please make sure the device to link with has been added to the app, and is assigned to the preferred room.\n2.Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    supportedLinkageDevices: 'Can be linked with the following devices',
    linkageDistanceTip: 'Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    linkageRemoveTip: 'If the linked Bluetooth device needs to be changed, please remove link first.',
    link: 'Link',
    removeLink: 'Remove link',
    linkFail: 'Couldn\'t link',
    removeLinkFail: 'Couldn\'t remove the link',
    linkConfirm: 'Link with this device now?',
    removeLinkConfirm: 'Remove link now?',
    linking: 'Linking…',
    pluginVersion: 'Plugin version number',
    helpAndFeedback: 'Yardım ve Geri Bildirim'
  },
  nl: {
    setting: 'Instellingen',
    featureSetting: 'Apparaatinstellingen',
    commonSetting: 'Algemene instellingen',
    name: 'Apparaatnaam',
    location: 'Locatiebeheer',
    memberSet: 'Toetsinstellingen',
    share: 'Apparaat delen',
    btGateway: 'BLE-gateway',
    voiceAuth: 'Autorisatie via spraak',
    ifttt: 'Automatisering',
    firmwareUpgrade: 'Updates van het apparaat',
    more: 'Extra instellingen',
    help: 'Help',
    legalInfo: 'Legale informatie',
    deleteDevice: 'Apparaat verwijderen',
    autoUpgrade: 'Firmware automatisch bijwerken',
    checkUpgrade: 'Controleren op firmware-updates',
    security: 'Beveiligingsinstellingen',
    networkInfo: 'Netwerkgegevens',
    feedback: 'Mijn feedback',
    timezone: 'Tijdzone van het apparaat',
    addToDesktop: 'Toevoegen aan het startscherm',
    // MHDatePicker
    cancel: 'Cancel',
    ok: 'Confirm',
    am: 'AM',
    pm: 'PM',
    months: 'months',
    days: 'days',
    hours: 'hours',
    minutes: 'minutes',
    seconds: 'seconds',
    month: 'month',
    day: 'day',
    hour: 'hour',
    minute: 'minute',
    second: 'second',
    yearUnit: '',
    monthUnit: '',
    dayUnit: '',
    hourUnit: '',
    minuteUnit: '',
    secondUnit: '',
    dateSubTitle: '{0}-{1}-{2}', // 2019-06-03
    time24SubTitle: '{0}:{1}', // 11:43
    time12SubTitle: '{1}:{2} {0}', // 11:43 am
    singleSubTitle: '{0} {1}', // 1 hour | 2 hours
    // 升级相关
    firmwareUpgradeExit: 'Afsluiten',
    firmwareUpgradeUpdate: 'Nu updaten',
    firmwareUpgradeLook: 'Nu rondkijken',
    firmwareUpgradeForceUpdate: 'De huidige firmware is mogelijk te oud om bepaalde functies uit te voeren. Update naar de nieuwste versie voor een betere ervaring.',
    firmwareUpgradeForceUpdating: 'Uw toestel is aan het updaten, probeer het later nog eens',
    firmwareUpgradeNew_pre: 'Firmware-update',
    firmwareUpgradeNew_sub: 'beschikbaar. Nu updaten',
    handling: 'Verwerken...',
    error: 'Kon niet werken, probeer het later opnieuw',
    createLightGroup: 'Create light group(new)',
    manageLightGroup: 'Manage devices(new)',
    deleteLightGroup: 'Disband light group',
    linkDevice: 'Link devices',
    noSuppurtedLinkageDevice: 'No devices available for linking now',
    noSuppurtedLinkageTip: '1.Please make sure the device to link with has been added to the app, and is assigned to the preferred room.\n2.Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    supportedLinkageDevices: 'Can be linked with the following devices',
    linkageDistanceTip: 'Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    linkageRemoveTip: 'If the linked Bluetooth device needs to be changed, please remove link first.',
    link: 'Link',
    removeLink: 'Remove link',
    linkFail: 'Couldn\'t link',
    removeLinkFail: 'Couldn\'t remove the link',
    linkConfirm: 'Link with this device now?',
    removeLinkConfirm: 'Remove link now?',
    linking: 'Linking…',
    pluginVersion: 'Plugin version number',
    helpAndFeedback: 'Help & Feedback'
  },
  pt: {
    setting: 'Configurações',
    featureSetting: 'Configurações do dispositivo',
    commonSetting: 'Configurações gerais',
    name: 'Nome do dispositivo',
    location: 'Gerenciamento de localização',
    memberSet: 'Configurações do tecla',
    share: 'Compartilhar dispositivo',
    btGateway: 'Gateway BLE',
    voiceAuth: 'Autorização de voz',
    ifttt: 'Automação',
    firmwareUpgrade: 'Atualizações de dispositivo',
    more: 'Configurações adicionais',
    help: 'Ajuda',
    legalInfo: 'Informação legal',
    deleteDevice: 'Excluir dispositivo',
    autoUpgrade: 'Atualizar automaticamente o firmware',
    checkUpgrade: 'Verificar se há atualizações de firmware',
    security: 'Configurações de segurança',
    networkInfo: 'Informações de rede',
    feedback: 'Meu feedback',
    timezone: 'Fuso horário do dispositivo',
    addToDesktop: 'Adicionar à tela de início',
    // MHDatePicker
    cancel: 'Cancel',
    ok: 'Confirm',
    am: 'AM',
    pm: 'PM',
    months: 'months',
    days: 'days',
    hours: 'hours',
    minutes: 'minutes',
    seconds: 'seconds',
    month: 'month',
    day: 'day',
    hour: 'hour',
    minute: 'minute',
    second: 'second',
    yearUnit: '',
    monthUnit: '',
    dayUnit: '',
    hourUnit: '',
    minuteUnit: '',
    secondUnit: '',
    dateSubTitle: '{0}-{1}-{2}', // 2019-06-03
    time24SubTitle: '{0}:{1}', // 11:43
    time12SubTitle: '{1}:{2} {0}', // 11:43 am
    singleSubTitle: '{0} {1}', // 1 hour | 2 hours
    // 升级相关
    firmwareUpgradeExit: 'Sair',
    firmwareUpgradeUpdate: 'Atualizar agora',
    firmwareUpgradeLook: 'Ver agora',
    firmwareUpgradeForceUpdate: 'O firmware atual pode ser muito antigo para executar alguns recursos. Atualize para a versão mais recente para obter uma melhor experiência.',
    firmwareUpgradeForceUpdating: 'Seu dispositivo está sendo atualizado. Tente novamente mais tarde',
    firmwareUpgradeNew_pre: 'Atualização de firmware',
    firmwareUpgradeNew_sub: 'disponível. Atualizar agora',
    handling: 'Processando...',
    error: 'Não foi possível operar, tente novamente mais tarde',
    createLightGroup: 'Create light group(new)',
    manageLightGroup: 'Manage devices(new)',
    deleteLightGroup: 'Disband light group',
    linkDevice: 'Link devices',
    noSuppurtedLinkageDevice: 'No devices available for linking now',
    noSuppurtedLinkageTip: '1.Please make sure the device to link with has been added to the app, and is assigned to the preferred room.\n2.Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    supportedLinkageDevices: 'Can be linked with the following devices',
    linkageDistanceTip: 'Please keep the Bluetooth device to link with within a certain distance of this device, otherwise it will be unable to link.',
    linkageRemoveTip: 'If the linked Bluetooth device needs to be changed, please remove link first.',
    link: 'Link',
    removeLink: 'Remove link',
    linkFail: 'Couldn\'t link',
    removeLinkFail: 'Couldn\'t remove the link',
    linkConfirm: 'Link with this device now?',
    removeLinkConfirm: 'Remove link now?',
    linking: 'Linking…',
    pluginVersion: 'Plugin version number',
    helpAndFeedback: 'Ajuda e feedback'
  }
});
export default strings;
export { formatString };