var LocalizedStrings = require("../../CommonModules/LocalizedStrings");
let MHLocalizableString = new LocalizedStrings({
  "en": {
    // 翻译好的
    "setting": "setting",
    "featureSetting": "Shortcut settings",
    "commonSetting": "Common settings",
    "deviceName": "Device name",
    "locationManagement": "Locations",
    "shareDevice": "Share device",
    "ifttt": "Automation",
    "firmwareUpgrate": "Check for firmware updates",
    "moreSetting": "Additional settings",
    "addToDesktop": "Add to Home screen",
    "bluetoothGateway": "Bluetooth Gateway",
    "resetDevice": "Remove device",
    "licenseAndPolicy": "User Agreement & Privacy Policy",
    "license": "Software License and Service Agreement",
    "policy": "Privacy Policy",
    "licenseURL": "license_en.html",
    "policyURL": "privacy_en.html",
    // 自己翻译的
    "monday": "Mon",
    "tuesday": "Tue",
    "wednesday": "Wed",
    "thursday": "Thu",
    "friday": "Fri",
    "saturday": "Sat",
    "sunday": "Sun",
    "sundayW": "Sun",
    "mondayW": "Mon",
    "tuesdayW": "Tue",
    "wednesdayW": "Wed",
    "thursdayW": "Thu",
    "fridayW": "Fri",
    "saturdayW": "Sat",
    "beijing": "Beijing",
    "city": "City",
    "province": "Province",
    "Min": "Min",
    "Sec": "Sec",
    "fetchConfigVersionFail": "Retrieving configuration version failed, please check your network and try again",
    // 不用翻译的
    "clockTipExample": "小爱同学，明天早上七点叫醒我",
    "reminderTipExample": "小爱同学，提醒我15分钟后喝水",
    "countdownTipExample": "小爱同学，设定一个2分钟倒计时",
    "travelTipExample": "小爱同学，今天五环路况怎么样",
    "weatherTipExample": "小爱同学，今天晚上天气怎么样",
    "travelTip1": "小爱同学，去公司需要多久",
    "travelTip2": "小爱同学，去公司路上堵吗",
    "travelTip3": "小爱同学，坐地铁去天安门需要多久",
    "travelTip4": "小爱同学，现在去首都机场大概需要多久",
    "weatherTip1": "小爱同学，今天晚上天气怎么样",
    "weatherTip2": "小爱同学，明天下雨吗",
    "weatherTip3": "小爱同学，上海现在下雨吗",
    "weatherTip4": "小爱同学，重庆明天天气怎么样",
    "weatherTip5": "小爱同学，纽约明天要带伞吗",
    "weatherTip6": "小爱同学，西雅图明天天气怎么样",
    // 单复数 / placeholder
    "copy": "item",
    "copys": "items",
    "item": "piece",
    "items": "pieces",
    "day": "{0}day",
    "days": "{0}days",
    "hour": "{0}hour",
    "hours": "{0}hours",
    "minute": "{0}minute",
    "minutes": "{0}minutes",
    "bell": "Bell after {0} {1} {2}",
    "monthDate": "{0}.{1}",
    "date": "",
    "am": "AM",
    "pm": "PM",
    "amWithTime": "{0} AM",
    "pmWithTime": "{0} PM",
    "onlyCloseOnce": "Close only at {0}",
    //
    "clock": "Alarm",
    "reminder": "Reminder",
    "countdown": "Countdown",
    "smartHome": "Smart home",
    "chatRecord": "Dialog record",
    "fetchRingOptions": "Retrieving ringtone configuration failed",
    "fetchWorkdayOptions": "Retrieving working days configuration failed",
    "travel": "Travel",
    "weather": "Weather",
    "clockNote": "Alarm note",
    "enterNote": "Input note",
    "noClockSet": "Alarm not set",
    "start": "Start",
    "startDate": "Start date",
    "setClock": "Set alarms",
    "setReminder": "Set reminders",
    "noClockAble": "Alarm is off",
    "noReminderSet": "Reminder not set",
    "noReminderAble": "Reminder expired",
    "noCountdownSet": "Countdown not enabled",
    "skillCenter": "Technical center",
    "smartHomeSubTitle": "Make your home understand you better",
    "chatRecordSubTitle": "View your conversation history with Mi AI Assistant Clock",
    "travelSubTitle": "How long does it take to travel to work?",
    "weatherSubTitle": "Is it raining today in my partner's city?",
    "today": "Today",
    "tomorrow": "Tomorrow",
    "enabling": "On",
    "unopened": "Off",
    "allRight": "OK",
    "once": "Once",
    "everyday": "Daily",
    "montofri": "Monday to Friday",
    "weekend": "Weekends",
    "workday": "Working days",
    "holiday": "Statutory holidays",
    "everyweek": "Weekly",
    "twoweek": "Every two weeks",
    "monthly": "Monthly",
    "yearly": "Yearly",
    "custom": "Custom",
    "repeat": "Recurrence",
    "endRepeat": "End recurrence",
    "alwaysRepeat": "No end date",
    "ring": "Ringtone",
    "snooze": "Snooze",
    "snoozeTip": "After setting Snooze, it will ring again 10 minutes later if you did not turn off the ringtone",
    "snoozeCloseTip": "After enabling the snooze, you need to press the button on top to turn it off when it rings",
    "deleteAfterBell": "Delete this alarm after ringing",
    "cancel": "Cancel",
    "ok": "OK",
    "save": "Save",
    "saved": "Saved successfully",
    "event": "Events",
    "enterEvent": "Input event",
    "enterAddress": "Input address",
    "noRemindAgain": "Disable reminders",
    "gotIt": "OK",
    "prompt": "Notifications",
    "maxWordLimit": "Maximum limit of 20 characters exceeded",
    "noCircleAlert": "Recurrence cannot be empty. Please select again.",
    "noEventAlert": "Event cannot be empty. Please fill in again.",
    "updateClockFailure": "Updating alarm failed",
    "addClockFailure": "Adding alarm failed",
    "updateReminderFailure": "Updating reminder failed",
    "addReminderFailure": "Adding reminder failed",
    "updateStatusFailure": "Updating status failed",
    //
    "deleteOneClockConfirm": "Delete the selected alarm?",
    "deleteOneReminderConfirm": "Delete the selected reminder?",
    "deleteOneTimerConfirm": "Delete the selected countdown?",
    //
    "deleteClockConfirm": "Delete selected alarms?",
    "deleteReminderConfirm": "Delete selected reminders?",
    "deleteTimerConfirm": "Delete selected countdowns?",
    "cancelTimerConfirm": "End the countdown?",
    "sameTimerExist": "A countdown with the same period already exists",
    "end": "End",
    "noEnd": "Don't end",
    "tag": "Label",
    "youCanSayLikeThis": "You can just say to the clock",
    "delete": "Delete",
    "selectAll": "Select all",
    "selectNone": "Deselect all",
    "selectItems": "Please select an item",
    "customCircle": "Custom",
    "travelSetting": "Travel settings",
    "oneCountdown": "Single countdown",
    "closeClock": "Turn off recurring alarms",
    "closeThisClock": "Turn off this recurring alarm",
    "maxClockLimit": "You can create up to 30 alarms. Please delete the alarms that are not used frequently and add new ones",
    "maxReminderLimit": "You can create up to 80 reminders. Please delete the old reminders and then add new ones",
    "maxTimerLimit": "You can create up to 100 countdowns. Please delete some countdowns and then add new ones",
    "pause": "Pause",
    "resume": "Continue",
    "travelTitle1": "Inquire about traffic info",
    "travelTitle2": "Inquire about the time required to go to a location",
    "car": "Driving",
    "bus": "By bus",
    "bike": "Riding",
    "walk": "Walking",
    "homePlaceholder": "Home address not added yet",
    "workPlaceholder": "Company address not added yet",
    "travelPlaceholder": "Filling in your travel preferences will help with travel advice",
    "licensePlatePlaceholder": "Filling in the number plate will help with travel advice",
    "arriveTimePlaceholder": "Filling in the arrival time will help with travel advice",
    "addressTip": "The set address will be used to provide information and advice on weather and travel",
    "licensePlateModalTitle1": "Filling in the number plate",
    "licensePlateModalTitle2": "will help with travel services",
    "enterLicensePlate": "Input number plate",
    "arriveTime": "Arrival time",
    "clockPlace": "Clock location",
    "home": "Home",
    "work": "Company",
    "travelPreference": "Travel preferences",
    "licensePlate": "Number plate",
    "weatherTitle1": "Inquire about local weather information",
    "weatherTitle2": "Inquire about weather in national cities",
    "weatherTitle3": "Inquire about weather in international cities",
    "loadingRingOptions": "Loading ringtone list…",
    "defaultRing": "Default ringtone",
    "lightOnTop": "Buttons indicator on top",
    "timeSystem": "24-hour clock display",
    "volume": "Volume",
    "fetchDefaultRingFailure": "Failed to retrieve the default ringtone. Please try again.",
    "fetchLightStatusFailure": "Failed to retrieve the status indicator light. Please try again.",
    "fetchTimeSystemFailure": "Failed to retrieve the 24-hour format. Please try again.",
    "fetchVolumeFailure": "Failed to retrieve the volume. Please try again.",
    "updateDefaultRingFailure": "Failed to configure the default ringtone. Please try again.",
    "updateLightStatusFailure": "Failed to update the status indicator light. Please try again.",
    "updateTimeSystemFailure": "Failed to update the 24-hour format. Please try again.",
    "updateVolumeFailure": "Failed to change the volume. Please try again.",
    "homeNone": "Please fill in your home address first",
    "workNone": "Please fill in your company address first",
    "illegalLicensePlate": "The number plate is illegal",
    "setTravelInfoSuccess": "Travel information set successfully",
    "expired": "Expired",
    year: '',
    month: '',
    day: '',
    hour: '',
    minute: '',
    am: 'AM',
    pm: 'PM'
  },
  "zh-CN": {
    // 翻译好的
    "setting": "设置",
    "featureSetting": "功能设置",
    "commonSetting": "通用设置",
    "deviceName": "设备名称",
    "locationManagement": "位置管理",
    "shareDevice": "设备共享",
    "ifttt": "智能",
    "firmwareUpgrate": "检查固件升级",
    "moreSetting": "更多设置",
    "addToDesktop": "添加到桌面",
    "bluetoothGateway": "蓝牙网关",
    "resetDevice": "删除设备",
    "licenseAndPolicy": "使用条款和隐私政策",
    "license": "软件许可及服务协议",
    "policy": "隐私政策",
    "licenseURL": "license_zh.html",
    "policyURL": "privacy_zh.html",
    // 自己翻译的
    "monday": "星期一",
    "tuesday": "星期二",
    "wednesday": "星期三",
    "thursday": "星期四",
    "friday": "星期五",
    "saturday": "星期六",
    "sunday": "星期天",
    "sundayW": "周日",
    "mondayW": "周一",
    "tuesdayW": "周二",
    "wednesdayW": "周三",
    "thursdayW": "周四",
    "fridayW": "周五",
    "saturdayW": "周六",
    "beijing": "北京",
    "Min": "分",
    "Sec": "秒",
    "city": "城市",
    "province": "省份",
    "fetchConfigVersionFail": "获取铃声配置版本失败，请检查网络后重试",
    // 不用翻译的
    "clockTipExample": "小爱同学，明天早上七点叫醒我",
    "reminderTipExample": "小爱同学，提醒我15分钟后喝水",
    "countdownTipExample": "小爱同学，设定一个2分钟倒计时",
    "travelTipExample": "小爱同学，今天五环路况怎么样",
    "weatherTipExample": "小爱同学，今天晚上天气怎么样",
    "travelTip1": "小爱同学，去公司需要多久",
    "travelTip2": "小爱同学，去公司路上堵吗",
    "travelTip3": "小爱同学，坐地铁去天安门需要多久",
    "travelTip4": "小爱同学，现在去首都机场大概需要多久",
    "weatherTip1": "小爱同学，今天晚上天气怎么样",
    "weatherTip2": "小爱同学，明天下雨吗",
    "weatherTip3": "小爱同学，上海现在下雨吗",
    "weatherTip4": "小爱同学，重庆明天天气怎么样",
    "weatherTip5": "小爱同学，纽约明天要带伞吗",
    "weatherTip6": "小爱同学，西雅图明天天气怎么样",
    // 单复数 / placeholder
    "copy": "个",
    "copys": "个",
    "item": "条",
    "items": "条",
    "day": "{0}天",
    "days": "{0}天",
    "hour": "{0}小时",
    "hours": "{0}小时",
    "minute": "{0}分",
    "minutes": "{0}分",
    "bell": "{0}{1}{2}后响铃",
    "monthDate": "{0}月{1}日",
    "date": "日",
    "am": "上午",
    "pm": "下午",
    "amWithTime": "上午{0}",
    "pmWithTime": "下午{0}",
    "onlyCloseOnce": "仅在{0}关闭一次",
    //
    "clock": "闹钟",
    "reminder": "提醒",
    "countdown": "倒计时",
    "smartHome": "智能家居",
    "chatRecord": "对话记录",
    "fetchRingOptions": "获取铃声配置失败",
    "fetchWorkdayOptions": "获取工作日配置失败",
    "travel": "出行",
    "weather": "天气",
    "clockNote": "闹钟备注",
    "enterNote": "输入备注",
    "noClockSet": "未设置闹钟",
    "start": "开始",
    "startDate": "开始日期",
    "setClock": "设置闹钟",
    "setReminder": "设置提醒",
    "noClockAble": "闹钟未开启",
    "noReminderSet": "未设置提醒",
    "noReminderAble": "提醒已关闭",
    "noCountdownSet": "未启用倒计时",
    "skillCenter": "技能中心",
    "smartHomeSubTitle": "让你的家更懂你的话",
    "chatRecordSubTitle": "查看你和小爱的对话记录",
    "travelSubTitle": "现在出行，到公司需要多久?",
    "weatherSubTitle": "Ta在的城市，今天下雨了吗？",
    "today": "今天",
    "tomorrow": "明天",
    "enabling": "正在启用",
    "unopened": "未开启",
    "allRight": "好的",
    "once": "仅一次",
    "everyday": "每天",
    "montofri": "周一至周五",
    "weekend": "周末",
    "workday": "法定工作日",
    "holiday": "法定节假日",
    "everyweek": "每周",
    "twoweek": "每两周",
    "monthly": "每月",
    "yearly": "每年",
    "custom": "自定义",
    "repeat": "重复",
    "endRepeat": "结束重复",
    "alwaysRepeat": "一直重复",
    "ring": "铃声",
    "snooze": "懒人闹钟",
    "snoozeTip": "设置懒人闹钟后，闹钟响铃未关闭则十分钟后再次响铃",
    "snoozeCloseTip": "开启懒人闹钟后，闹钟响铃时，需要按顶部按钮关闭",
    "deleteAfterBell": "响铃后删除此闹钟",
    "cancel": "取消",
    "ok": "确认",
    "save": "保存",
    "saved": "保存成功",
    "event": "事件",
    "enterEvent": "输入事件",
    "enterAddress": "输入地址",
    "noRemindAgain": "不再提示",
    "gotIt": "我知道了",
    "prompt": "提示",
    "maxWordLimit": "已超最大输入限制20个字",
    "noCircleAlert": "重复不能为空，请重新选择。",
    "noEventAlert": "事件不能为空，请重新填写。",
    "updateClockFailure": "更新闹钟失败",
    "addClockFailure": "添加闹钟失败",
    "updateReminderFailure": "更新提醒失败",
    "addReminderFailure": "添加提醒失败",
    "updateStatusFailure": "更新状态失败",
    //
    "deleteOneClockConfirm": "你是否要删除该闹钟",
    "deleteOneReminderConfirm": "你是否要删除该提醒",
    "deleteOneTimerConfirm": "你是否要删除该倒计时",
    //
    "deleteClockConfirm": "你是否要删除这些闹钟",
    "deleteReminderConfirm": "你是否要删除这些提醒",
    "deleteTimerConfirm": "你是否要删除这些倒计时",
    "cancelTimerConfirm": "确定要结束倒计时么？",
    "sameTimerExist": "相同时间的倒计时已存在",
    "end": "结束",
    "noEnd": "不结束",
    "tag": "标签",
    "youCanSayLikeThis": "你可以直接对闹钟说",
    "delete": "删除",
    "selectAll": "全选",
    "selectNone": "全不选",
    "selectItems": "请选择项目",
    "customCircle": "自定义重复",
    "travelSetting": "出行设置",
    "oneCountdown": "单次倒计时",
    "closeClock": "关闭重复闹钟",
    "closeThisClock": "关闭这个重复闹钟",
    "maxClockLimit": "最多只能创建30个闹钟，请删除不常用的闹钟后再添加",
    "maxReminderLimit": "最多只能创建80条提醒，请删除过期的提醒后再添加",
    "maxTimerLimit": "最多只能创建100条倒计时，请删除一些倒计时后再添加",
    "pause": "暂停",
    "resume": "继续",
    "travelTitle1": "查询交通信息",
    "travelTitle2": "查询去某个地点所需要的时间",
    "car": "驾车",
    "bus": "公交",
    "bike": "骑行",
    "walk": "步行",
    "homePlaceholder": "你还没添加家庭地址",
    "workPlaceholder": "你还没添加公司地址",
    "travelPlaceholder": "填写出行偏好有助于为你提供出行建议",
    "licensePlatePlaceholder": "填写车牌号有助于为你提供出行建议",
    "arriveTimePlaceholder": "填写到达时间有助于为你提供出行建议",
    "addressTip": "设置地址将用于为你提供天气与出行的信息和建议",
    "licensePlateModalTitle1": "填写车牌号",
    "licensePlateModalTitle2": "有助于我们为你提供出行服务",
    "enterLicensePlate": "输入车牌号",
    "arriveTime": "到达时间",
    "clockPlace": "闹钟摆放地点",
    "home": "家",
    "work": "公司",
    "travelPreference": "出行偏好",
    "licensePlate": "车牌号",
    "weatherTitle1": "查询当地天气信息",
    "weatherTitle2": "查询全国城市天气",
    "weatherTitle3": "查询国际城市天气",
    "loadingRingOptions": "铃声列表加载中...",
    "defaultRing": "默认铃声",
    "lightOnTop": "顶部按键指示灯",
    "timeSystem": "24小时制时间显示",
    "volume": "音量",
    "fetchDefaultRingFailure": "获取默认铃声失败，请重试。",
    "fetchLightStatusFailure": "获取指示灯状态失败，请重试。",
    "fetchTimeSystemFailure": "获取小时制失败，请重试。",
    "fetchVolumeFailure": "获取音量失败，请重试。",
    "updateDefaultRingFailure": "设置默认铃声失败，请重试。",
    "updateLightStatusFailure": "更新指示灯状态失败，请重试。",
    "updateTimeSystemFailure": "更新小时制失败，请重试。",
    "updateVolumeFailure": "更新音量失败，请重试。",
    "homeNone": "请先填写家庭地址",
    "workNone": "请先填写公司地址",
    "illegalLicensePlate": "车牌号不合法",
    "setTravelInfoSuccess": "出行信息设置成功",
    "expired": "已过期",
    "closed": "已关闭",
    year: '年',
    month: '月',
    day: '日',
    hour: '时',
    minute: '分',
    am: '上午',
    pm: '下午'
  },
  "zh-TW": {
    setting: "設置",
    featureSetting: "功能設定",
    commonSetting: "一般設定",
    deviceName: "裝置名稱",
    locationManagement: "位置管理",
    shareDevice: "裝置共用",
    ifttt: "智慧",
    firmwareUpgrate: "檢查韌體更新",
    moreSetting: "更多設定",
    addToDesktop: "新增到桌面",
    resetDevice: "刪除裝置",
    licenseAndPolicy: "用戶協議和隱私政策",
    year: '年',
    month: '月',
    day: '日',
    hour: '时',
    minute: '分',
    am: '上午',
    pm: '下午'
  },
  "zh-HK": {
    setting: "設置",
    featureSetting: "feature setting",
    commonSetting: "一般設定",
    deviceName: "裝置名稱",
    locationManagement: "位置管理",
    shareDevice: "裝置共用",
    ifttt: "智慧",
    firmwareUpgrate: "檢查韌體更新",
    moreSetting: "更多設定",
    addToDesktop: "新增到桌面",
    resetDevice: "刪除裝置",
    licenseAndPolicy: "用戶協議和隱私政策",
    year: '年',
    month: '月',
    day: '日',
    hour: '',
    minute: '',
    am: '上午',
    pm: '下午'
  },

  "ko": {
    featureSetting: "바로가기 설정",
    commonSetting: "일반 설정",
    deviceName: "기기 이름",
    locationManagement: "위치",
    shareDevice: "기기 공유",
    ifttt: "자동화",
    firmwareUpgrate: "펌웨어 업데이트 확인",
    moreSetting: "추가 설정",
    addToDesktop: "홈 화면에 추가",
    resetDevice: "기기 제거",
    licenseAndPolicy: "이용 약관 & 개인 정보 보호 정책",
  }
});

exports.string = MHLocalizableString
